# Site settings
title: "Istruzione e Formazione Tecnica Superiore 2018 @ DISI"
email: danilo.pianini@unibo.it
description: > # this means to ignore newlines until "baseurl:"
  Materiale per il modulo di Elementi di Programmazione e Sviluppo di Applicazioni
baseurl: "/ifts"
url: "http://localhost:3838"
port: 3838
twitter_username: DanySK86
github_username:  danysk
encoding: utf-8

# Build settings
markdown: kramdown
